{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "44388e1d-0f64-46fa-88bd-a872b2813e86",
   "metadata": {},
   "source": [
    "# Compliance Streaming Data Product Framework — Pre-Development\n",
    "\n",
    "## Purpose\n",
    "To define the **rules of the system before it is built**, ensuring:\n",
    "- Deterministic behavior by design\n",
    "- Contract-first ingestion\n",
    "- Auditable failure handling\n",
    "- Clear separation between execution and evidence\n",
    "\n",
    "This framework intentionally does **not** describe implementation details.\n",
    "\n",
    "---\n",
    "\n",
    "## Status\n",
    "**Pre-Development Framework (Rulebook)**  \n",
    "This document defines **requirements and proof expectations only**.  \n",
    "No claims in this document assert completed execution.\n",
    "\n",
    "---\n",
    "\n",
    "## Scope\n",
    "Included:\n",
    "- Local streaming data pipeline (single source, append-only events)\n",
    "- Continuous watcher with checkpointed progress\n",
    "- Validation, flag emission, and audit expectations\n",
    "- Evidence files to be produced post-development\n",
    "\n",
    "Explicitly excluded:\n",
    "- Kafka / cloud infrastructure\n",
    "- Distributed scaling\n",
    "- SLA or latency guarantees\n",
    "- External orchestration\n",
    "- Performance optimisation\n",
    "- Streaming analytics or alerting systems\n",
    "\n",
    "---\n",
    "\n",
    "## Success Definition & Failure Modes (NON-NEGOTIABLE)\n",
    "\n",
    "### Success Metrics (must be provable)\n",
    "- No persisted event is skipped\n",
    "- Deterministic outputs given identical inputs and configuration\n",
    "- Contract enforcement with zero tolerated violations\n",
    "- Flag events emitted deterministically for rule breaches\n",
    "- Restart resumes from last checkpointed offset\n",
    "\n",
    "### Explicit Failure Modes\n",
    "- Contract violation (schema, type, domain) → fail-fast, no flags emitted\n",
    "- Ordering or duplicate policy violation → fail-fast\n",
    "- I/O or write failure → fail-fast, non-zero exit\n",
    "- Any unexpected exception → fail-fast, non-zero exit\n",
    "\n",
    "---\n",
    "\n",
    "## Design Principles\n",
    "1. **No implicit guarantees** — guarantees apply only to persisted events\n",
    "2. **Fail fast** — invalid events do not enter state or rule evaluation\n",
    "3. **Determinism is defined, not assumed**\n",
    "4. **Evidence is mandatory; narrative is insufficient**\n",
    "5. **Notebook is review-only, never execution**\n",
    "\n",
    "---\n",
    "\n",
    "## Core Requirements and Evidence Mapping\n",
    "\n",
    "### 1. Ingestion Contract Enforcement\n",
    "**Requirement**  \n",
    "All persisted events must conform to a predefined schema and domain contract before state updates or rule evaluation.\n",
    "\n",
    "**Evidence Files**\n",
    "- `src/contracts/event_contract.py`\n",
    "- `outputs/reports/validation_report.json`\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: all required fields present, types valid, domain rules satisfied  \n",
    "- FAIL: any violation → watcher exits non-zero, no flags emitted\n",
    "\n",
    "---\n",
    "\n",
    "### 2. Deterministic Processing\n",
    "**Requirement**  \n",
    "Given identical persisted inputs and configuration, the watcher must emit identical flag outputs.\n",
    "\n",
    "**Evidence Files**\n",
    "- `logs/run_<run_id>.json`\n",
    "- Input stream slice hash\n",
    "- Flag output hash\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: identical hashes across repeated runs  \n",
    "- FAIL: any hash mismatch\n",
    "\n",
    "---\n",
    "\n",
    "### 3. Flag Emission Contract\n",
    "**Requirement**  \n",
    "When a rule is breached, the system emits a **flag event**.\n",
    "\n",
    "**Flag Fields (required)**\n",
    "- user_id\n",
    "- flag_id \n",
    "- rule_name  \n",
    "- metric_value  \n",
    "- threshold  \n",
    "- window  \n",
    "- event_id  \n",
    "- event_time  \n",
    "- ingest_time  \n",
    "\n",
    "**Evidence Files**\n",
    "- `outputs/flags/flags.log` (append-only, JSONL)\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: flags conform to contract and match rule conditions  \n",
    "- FAIL: missing fields or inconsistent values\n",
    "\n",
    "---\n",
    "\n",
    "### 4. Failure Handling\n",
    "**Requirement**  \n",
    "Any validation or processing failure must:\n",
    "- Stop execution immediately\n",
    "- Prevent flag emission for the failing event and post the failure\n",
    "- Preserve prior outputs\n",
    "\n",
    "**Evidence Files**\n",
    "- `logs/run_<run_id>.json`\n",
    "- Non-zero process exit code\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: failure recorded, no new flags written  \n",
    "- FAIL: silent failure or partial output\n",
    "\n",
    "---\n",
    "\n",
    "### 5. Observability & Traceability\n",
    "**Requirement**  \n",
    "Each watcher run must be traceable.\n",
    "\n",
    "**Evidence Files**\n",
    "- `logs/run_<run_id>.json` containing:\n",
    "  - run_id, started_at, ended_at, status\n",
    "  - contract name/version\n",
    "  - paths (stream, flags)\n",
    "  - offsets (resume_offset, final_offset)\n",
    "  - counts (events_read, events_valid, flags_emitted)\n",
    "  - error (if failed)\n",
    "\n",
    "- `outputs/reports/validation_report.json` containing:\n",
    "  - policy (ordering, duplicates)\n",
    "  - full failure counters (json_parse_failures, contract_failures, etc.)\n",
    "  - checkpoint offset + last_event_time\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: all fields populated  \n",
    "- FAIL: missing or incomplete metadata\n",
    "\n",
    "---\n",
    "\n",
    "### 6. Event-Time & Ordering Policy\n",
    "**Requirement**  \n",
    "The watcher enforces **arrival-order processing**.\n",
    "\n",
    "- Out-of-order `event_time` values are **not supported**\n",
    "- Ordering violations cause failure\n",
    "\n",
    "**Evidence Files**\n",
    "- `outputs/reports/validation_report.json` (ordering checks)\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: no ordering violations detected  \n",
    "- FAIL: any out-of-order event detected\n",
    "\n",
    "---\n",
    "\n",
    "### 7. Idempotency & Duplicate Policy\n",
    "**Requirement**  \n",
    "Duplicate events (by `event_id`) are **not supported** in v1.\n",
    "\n",
    "**Evidence Files**\n",
    "- `outputs/reports/validation_report.json` (duplicate checks)\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: all event_ids unique  \n",
    "- FAIL: any duplicate detected\n",
    "\n",
    "---\n",
    "\n",
    "### 8. Replay & Restart Guarantees\n",
    "**Requirement**  \n",
    "The watcher is **continuous** with checkpointed progress.\n",
    "\n",
    "Guarantees:\n",
    "- No loss is guaranteed only for events already persisted to the local stream\n",
    "- Restart resumes from the last checkpointed offset\n",
    "- Replay uses a captured stream slice for deterministic verification\n",
    "- Watcher runs until interrupted; continuous here means it polls and resumes, not an SLA\n",
    "\n",
    "**Evidence Files**\n",
    "- `logs/run_<run_id>.json`\n",
    "- `outputs/checkpoints/state.json`\n",
    "\n",
    "**Pass / Fail Criteria**\n",
    "- PASS: restart resumes correctly without skipping persisted events  \n",
    "- FAIL: offset regression or event loss\n",
    "\n",
    "---\n",
    "\n",
    "## Notebook Role\n",
    "The notebook is **not** part of execution.\n",
    "\n",
    "Notebook responsibilities:\n",
    "- Load logs, flags, validation reports\n",
    "- Verify determinism and rule behavior\n",
    "- Review restart and replay outcomes\n",
    "\n",
    "Notebook must not:\n",
    "- Execute watcher logic\n",
    "- Mutate state\n",
    "- Describe hypothetical behavior\n",
    "\n",
    "---\n",
    "\n",
    "## Versioning Rules\n",
    "- This document is **v1.0 (Pre-Development)** and frozen\n",
    "- Any change requires version bump (v1.1+)\n",
    "- Evidence is produced only by execution\n",
    "\n",
    "---\n",
    "\n",
    "## Evaluation Standard\n",
    "This framework is considered **complete** when:\n",
    "- Every requirement has corresponding evidence\n",
    "- All guarantees are provable via outputs and logs\n",
    "- No guarantees exceed what is explicitly stated\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "796ae405-eaeb-43ed-b554-be2118a1e94d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
